# ARGO Phase 2 Configuration Template
# Fill in actual values when deploying

# Redis Configuration
redis:
  host: ${REDIS_HOST}  # To be provided by Director
  port: 6379
  password: ${REDIS_PASSWORD}  # Optional
  db: 0
  decode_responses: true
  connection_pool:
    max_connections: 50
    max_idle_time: 30
    retry_on_timeout: true

# LLM API Configuration
llm:
  openai:
    api_key: ${OPENAI_API_KEY}  # To be provided by Director
    model: "gpt-4"
    max_tokens: 4096
    temperature: 0.7
  
  anthropic:
    api_key: ${ANTHROPIC_API_KEY}  # To be provided by Director
    model: "claude-3-opus-20240229"
    max_tokens: 4096
  
  google:
    api_key: ${GEMINI_API_KEY}  # To be provided by Director
    model: "gemini-1.5-pro"
    
# Agent Configuration
agents:
  orchestrator:
    enabled: true
    port: 8000
    max_concurrent_tasks: 10
    timeout_seconds: 300
  
  specialized:
    technical_architect:
      enabled: true
      capabilities: ["system_design", "tech_stack", "optimization"]
    
    creative_analyst:
      enabled: true
      capabilities: ["design", "content", "ideation"]
    
    research_scholar:
      enabled: true
      capabilities: ["research", "analysis", "data_mining"]
    
    execution_engineer:
      enabled: true
      capabilities: ["code_generation", "deployment", "testing"]

# Shared Context Configuration
context:
  episodic_memory:
    ttl_hours: 48
    max_size_mb: 100
  
  semantic_memory:
    storage: "redis"  # or "neo4j" when available
    index_update_interval: 3600
  
  procedural_memory:
    learning_rate: 0.1
    pattern_threshold: 3  # Minimum occurrences to learn pattern

# Lock Manager Configuration
locks:
  default_ttl_seconds: 30
  max_wait_time_seconds: 60
  deadlock_detection_interval: 5

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  log_level: "INFO"
  conflict_tracking: true
  performance_tracking: true

# System Configuration
system:
  project_id: "argo-813"
  region: "asia-northeast3"
  environment: "development"  # development | staging | production
  debug_mode: true